### ISSUE TITLE
any plan for h5ad (scanpy) version

### ISSUE THREAD

**Issue by M0hammadL** [ncborcherding/utility#1]
Hi 

thanks for sharing the data and letting the world use it for science!  
Would it be possible to also release the h5ad version of the file readable via scanpy? many people
use scanpy and would be great if you release it.

Best
Mo

**Comment by ncborcherding** [comment]
Hey Mo, 

Absolutely, that is my goal for the next data update. Do you prefer h5 or loom? 

Thanks,
Nick

**Comment by M0hammadL** [comment]
h5ad is the default for scanpy:

https://anndata.readthedocs.io/en/latest/anndata.AnnData.html

**Comment by ncborcherding** [comment]
Ok great - thanks for the info. I will post an update here when I get it converted. 

Nick

**Comment by grst** [comment]
Just read on twitter you are planning a scanpy-ecosystem version. 

You may want to consider loading the TCR data with scirpy: 
https://icbi-lab.github.io/scirpy/latest/tutorials/tutorial_io.html

**Comment by ncborcherding** [comment]
Thanks for the suggestion - will definitely look into it. Please feel free to make others as I am not as familiar with python as R!

**Comment by grst** [comment]
For full disclosure I need to add that I'm the main developer of scirpy.

Another very cool tool in the Python world is [conga](https://github.com/phbradley/conga) which focuses on the integration of TCR with gene expression data. We are working on adding a conga wrapper to scirpy. 

There's also [dandelion](https://github.com/zktuong/dandelion) but it is mostly specialized on BCR data.

**Comment by M0hammadL** [comment]
thanks, @grst  @ncborcherding  it would be really beneficial for further usage of the data and opening a new community!

PS: @grst is great, I use it all the time, keep on a good work!

**Comment by ncborcherding** [comment]
Thanks I appreciate the suggestion and I will have to check out scirpy more - I might ping you if I have questions - full disclosure, I wrote an R package for single-cell immune repertoire profiling - [scRepertoire](https://github.com/ncborcherding/scRepertoire) and am deeply interested in how people are using the interaction of TCR/GEX - which CONGA is definitely a great example.

thanks @M0hammadL and @grst for the suggestions!!

**Comment by ncborcherding** [comment]
Finally got .h5ad up for the sequencing runs, so I am going to close this - I have yet to merge/integrate all cells into a single object.
