### ISSUE TITLE
What does individual RDS file name indicates?

### ISSUE THREAD

**Issue by ZainulArifin1** [ncborcherding/utility#3]
Hi. First of all, thank you for making this repository.

I noticed that the individual RDS file is named based on some identifier like LB, EST, and BCT. Do these identifiers refer to the cancer type?

**Comment by ncborcherding** [comment]
Hey Zainul, 

Thanks for reaching out. The Sample ID was designed to try to convey information about the cancer, tissue type, patient ID,and sequencing run - if you have suggestions though, the repository has grown quite a bit. 

In case you did not figure it out - you are correct, generally, the first 1-2 letters is the cancer and the last letter is the tissue type. So for example 

- LB - is lung, blood, EST is Esophageal Tumor, BCT is basal cell tumor. 
- The runs are labeled then with a numeric by the order of entry into the repository - for example, LT1. 
- That LT1 may have associated samples such as normal lung tissue (which would be labeled as LN1 - keeping the same numerical samples). 
- Multiple samples from the same patient will get a subdesignation - for example, the patient BCT1 had 5 sequencing runs BCT1.1-5 with specific cell isolation and treatment timepoints. 

I will add the breakdown to the readme - that is my fault for not being clear. 

Thanks,
Nick
