### ISSUE TITLE
Cannot locate ‘ filtered_seuratObjects_harmony.rds’ in v0.0.4

### ISSUE THREAD

**Issue by lshen999** [ncborcherding/utility#4]
Hi,

As stated in the title, I cannot find the 'filtered_seuratObjects_harmony.rds' object in the [Version v0.0.4](https://zenodo.org/record/6325603), which exists only in [Version v0.0.1](https://zenodo.org/record/4995299).

Is there a newest harmonised filtered object that you could upload?

Thanks!

**Comment by ncborcherding** [comment]
As of right now - there is not a harmonized, fully integrated seurat object across all the cells in v0.0.4. It is being worked on and will post here when a new zenodo/full integrated seurat object is uploaded.
