### ISSUE TITLE
v.04 data with sample annotation

### ISSUE THREAD

**Issue by p-gueguen** [ncborcherding/utility#5]
Hello,

Thanks a lot for the nice repo! I was wondering if you had a version of the v0.4 datasets with annotated Type, Tissue, and the Cohort (with the GSE identifier for instance) in the metadata, like what you had for the v0.1 pipeline. 

I can retrieve most of it by your sample name nomenclature, but I think I will still miss the cohort identifier.

Thanks a lot for your help,
Paul

**Comment by ncborcherding** [comment]
Hey Paul, 

I am working on making a single integrated object which will include the cohort data. For now, each of the sequencing runs are summarized [here](https://github.com/ncborcherding/utility/blob/main/summaryInfo/sample.directory.xlsx). Hope that helps.

Nick

**Comment by p-gueguen** [comment]
Thank you for the quick answer, Nick! Looking forward to the updates on this. I had missed the excel file indeed. Is there any way to match these metadata to the samples of individual Seurat objects (ie. BCT1.1)?

Thanks!

Paul

**Comment by ncborcherding** [comment]
Hey Paul, 

All the seurat objects/anndata .h5 objects should follow the naming convention (such as BCT1.1). If you load the seurat object - the orig.ident variable is also using the naming convention. A summary of the sample id/naming convention is actually better described on the [dev branch](https://github.com/ncborcherding/utility/tree/dev).

Nick

**Comment by p-gueguen** [comment]
Thanks a lot Nick, that's very clear now. Have a great day.

Paul
