### ISSUE TITLE
Thoughts on updating CD8 atlas?

### ISSUE THREAD

**Issue by jeremymsimon** [ncborcherding/utility#9]
Saw this paper recently and I think some of the underlying sources are similar to yours. Curious to hear your thoughts about updating the CD8 atlas based on this meta-analysis, and potential utility (pun intended) for something like ProjecTILs?
https://www.nature.com/articles/s41592-024-02530-0

**Comment by ncborcherding** [comment]
@jeremymsimon 

Yes I saw that recent publication. I now have about 1000 sequencing runs that are in uTILity and still need to get time to collect everything together. 

As of right now, I do believe the most recent ProjecTILs human CD8 atlas is using uTILity

Nick
